# Generated by Django 3.0.5 on 2020-05-17 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.PositiveIntegerField()),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('payment_gateway', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(blank=True, choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'failed'), ('cancelled', 'cancelled')], null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transaction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
